name: sleep_model_env

channels:
  - conda-forge  # Dipindahkan ke atas untuk prioritas utama
  - defaults

dependencies:
  # --- Paket utama diinstal langsung via Conda untuk stabilitas ---
  - python=3.10
  - pandas
  - scikit-learn
  - mlflow=2.19.0  # Versi disesuaikan dengan panduan proyek

  # --- Pip tetap disertakan jika ada paket yang hanya tersedia di Pip ---
  - pip