name: sleep_quality_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow>=2.0.0
    - scikit-learn>=1.0.0
    - pandas>=1.3.0
    - numpy>=1.21.0
    - matplotlib>=3.4.0
    - seaborn>=0.11.0
