name: ML Training CI
on:
  push:
    branches: [main]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sleep_quality_env
        environment-file: MLProject/conda.yaml
        python-version: 3.12
    - name: Install dependencies
      run: |
        conda activate sleep_quality_env
        pip install mlflow==2.17.0
    - name: Run MLflow Project
      run: |
        mlflow run MLProject -P experiment_name=Sleep_Quality_Prediction_CI
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/