name: CI-CD ML Model

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah ini menggantikan 'setup-python' dan 'install mlflow'.
      # Ini akan menginstal Conda dan menginisialisasi shell dengan benar.
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Secara otomatis mengaktifkan lingkungan dasar conda
          auto-activate-base: true
          # Membuat conda dapat diakses dari semua langkah berikutnya
          activate-environment: ''

      # Langkah ini sekarang akan berjalan dengan sukses karena shell 
      # sudah mengenali perintah-perintah conda yang dieksekusi oleh mlflow
      - name: Run MLflow Project
        run: mlflow run ./MLProject