name: ML Training CI
on:
  push:
    branches: [main]
jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sleep_quality_env
        environment-file: MLProject/conda.yaml
        python-version: 3.10
        auto-activate-base: false
    - name: Debug Environment
      run: |
        conda info
        conda list
        pip list
        ls -R MLProject
    - name: Run MLflow Project
      run: |
        conda run -n sleep_quality_env mlflow run MLProject -P experiment_name=Sleep_Quality_Prediction_Yahya