name: CI-CD ML Model

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true

      - name: Install MLflow in Base Environment
        run: pip install mlflow==2.19.0

      # --- PERBAIKAN UTAMA ADA DI SINI ---
      - name: Run MLflow Project
        # Menambahkan 'shell: bash -l {0}' akan menjalankan perintah
        # dalam 'login shell', yang memastikan conda sudah terinisialisasi
        # dengan benar dan perintah 'activate' dapat ditemukan.
        shell: bash -l {0}
        run: mlflow run ./MLProject