name: CI-CD ML Model

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda and MLflow
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: sleep_model_env # Langsung aktivasi env dari conda.yaml
          environment-file: MLProject/conda.yaml # Tunjuk file env
          python-version: 3.10

      - name: Run MLflow Project
        shell: bash -l {0} # Pastikan shell diinisialisasi dengan benar untuk conda
        run: mlflow run ./MLProject