name: CI-CD ML Model

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ''

      # --- LANGKAH BARU YANG PENTING ---
      # Setelah conda siap, kita instal MLflow ke dalam environment dasar
      # yang sedang aktif di runner.
      - name: Install MLflow
        run: pip install mlflow==2.19.0

      # Sekarang, langkah ini akan berhasil karena perintah 'mlflow' sudah ada.
      - name: Run MLflow Project
        run: mlflow run ./MLProject